kind: Service
apiVersion: v1
metadata:
  name: use-service
spec:
  type: <SERVICE TYPE>
  selector:
    <LABELS>
  ports:
    - protocol: TCP
      port: <SERVICE PORT>
      targetPort: <CONTAINER PORT> # can be left out if targetPort = port
      nodePort: 30080